### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by aaronclong** [sculpt0r/vsc-ava-test-runner#12]
I'm using your extension, and really want to thank you for putting it together.

Could you publish it to [Open VSX](https://open-vsx.org/)?  [This is the registry third-party registry VSCodium, an open-source build of VS Code, uses for plugins](https://github.com/VSCodium/vscodium/issues/372).

**Comment by sculpt0r** [comment]
Hi @aaronclong - I'm glad to hear that :)

As soon as I find a little more time - I probably will :)

**Comment by sculpt0r** [comment]
That was fast: https://open-vsx.org/extension/sculpt0r/vsc-ava-test-runner

**Comment by aaronclong** [comment]
@sculpt0r thats exciting, thank you!
