### ISSUE TITLE
Parsing error with single-line comments

### ISSUE THREAD

**Issue by AaronPorts** [sculpt0r/vsc-ava-test-runner#8]
Looks like // comments are causing a parsing error:
```
* no Run | --watch | Debug *
test("404", async (t) => {
    t.is(statusCode, 404);
});
// test("405", async (t) => {
//     t.is(statusCode, 405);
// });
```

**Comment by sculpt0r** [comment]
Hi @AaronPorts - thanks for the report.

I'll take a look at this 🤞

**Comment by sculpt0r** [comment]
Seems like the issue occurs only if you comment the `test` line. Thanks again - I'll fix it.
